kind: Service
apiVersion: v1
metadata:
  name: orders
  labels:
    app: orders
spec:
  selector:
    app: orders
  ports:
    - port: 80
      targetPort: 7001
      name: http
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: orders
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: orders
        version: v1
    spec:
      containers:
        - name: orders
          image: helidonsockshop/orders-core:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 7001