kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: orders
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: orders
        version: v1
    spec:
      containers:
        - name: orders
          image: helidonsockshop/orders-core:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 7001