kind: Service
apiVersion: v1
metadata:
  name: payment
  labels:
    app: payment
spec:
  selector:
    app: payment
  ports:
    - port: 80
      targetPort: 7001
      name: http
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: payment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: payment
        version: v1
    spec:
      containers:
        - name: payment
          image: helidonsockshop/payment-core:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 7001