kind: Service
apiVersion: v1
metadata:
  name: catalogue  # for compatibility with the existing front-end implementation
  labels:
    app: catalog
spec:
  selector:
    app: catalog
  ports:
    - port: 80
      targetPort: 7001
      name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
        version: v1
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
        - name: catalog
          image: helidonsockshop/catalog-core:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 7001
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 400Mi
