apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db
  labels:
    name: payment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: payment-db
  template:
    metadata:
      labels:
        name: payment-db
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
      - name: payment-db
        image: mongo:4.2.2
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: payment-db
  labels:
    name: payment-db
spec:
  ports:
    # the port that this service should serve on
  - port: 27017
    targetPort: 27017
  selector:
    name: payment-db
