kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: shipping
spec:
  template:
    spec:
      containers:
        - name: shipping
          image: helidonsockshop/shipping-mongo:1.0.0
