kind: Service
apiVersion: v1
metadata:
  name: user  # for compatibility with the existing front-end implementation
  labels:
    app: users
spec:
  selector:
    app: users
  ports:
    - port: 80
      targetPort: 7001
      name: http
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: users
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: users
        version: v1
    spec:
      containers:
        - name: users
          image: helidonsockshop/users-core:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 7001