kind: Service
apiVersion: v1
metadata:
  name: user  # for compatibility with the existing front-end implementation
  labels:
    app: users
spec:
  selector:
    app: users
  ports:
    - port: 80
      targetPort: 7001
      name: http
