#
# Copyright (c) 2020 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.
#
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: orders
spec:
  cluster: sockshop
  role: orders
  replicas: 1
  image: helidonsockshop/orders-coherence:2.0.0-SNAPSHOT
  imagePullPolicy: Always
  env:
    - name: TRACING_HOST
      value: "jaeger-collector"
    - name: JAEGER_SAMPLER_TYPE
      value: "const"
    - name: JAEGER_SAMPLER_PARAM
      value: "1"
  application:
    main: io.helidon.microprofile.server.Main
  jvm:
    memory:
      heapSize: 100m
  ports:
    - name: http
      port: 7001
      service:
        name: orders
        port: 80
      serviceMonitor:
        enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1000m
      memory: 400Mi
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
