kind: Service
apiVersion: v1
metadata:
  name: front-end
  labels:
    app: front-end
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8079
  selector:
    app: front-end
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: front-end
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end
        image: weaveworksdemos/front-end:0.3.12
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8079
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
