kind: Service
apiVersion: v1
metadata:
  name: carts
  labels:
    app: carts
spec:
  selector:
    app: carts
  ports:
    - port: 80
      targetPort: 7001
      name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: carts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carts
  template:
    metadata:
      labels:
        app: carts
        version: v1
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
        - name: carts
          image: helidon/sockshop/carts-core:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 7001
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 400Mi
