kind: Service
apiVersion: v1
metadata:
  name: user  # for compatibility with the existing front-end implementation
  labels:
    app: users
spec:
  selector:
    app: users
  ports:
    - port: 80
      targetPort: 7001
      name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
        version: v1
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
        - name: users
          image: helidonsockshop/users-core:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7001
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 400Mi
