kind: Service
apiVersion: v1
metadata:
  name: shipping
  labels:
    app: shipping
spec:
  selector:
    app: shipping
  ports:
    - port: 80
      targetPort: 7001
      name: http
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: shipping
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shipping
        version: v1
    spec:
      containers:
        - name: shipping
          image: helidonsockshop/shipping-core:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 7001