kind: Service
apiVersion: v1
metadata:
  name: orders
  labels:
    app: orders
spec:
  selector:
    app: orders
  ports:
    - port: 80
      targetPort: 7001
      name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
        version: v1
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
        - name: orders
          image: helidonsockshop/orders-core:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7001
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 400Mi
