kind: Service
apiVersion: v1
metadata:
  name: carts
  labels:
    app: carts
spec:
  selector:
    app: carts
  ports:
    - port: 80
      targetPort: 7001
      name: http
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: carts
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: carts
        version: v1
    spec:
      containers:
        - name: carts
          image: helidonsockshop/carts-core:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 7001
